export const CREATE_CHECKOUT_SESSION_REQUEST = 'CREATE_CHECKOUT_SESSION_REQUEST';
export const CREATE_CHECKOUT_SESSION_SUCCESS = 'CREATE_CHECKOUT_SESSION_SUCCESS';
export const CREATE_CHECKOUT_SESSION_FAIL = 'CREATE_CHECKOUT_SESSION_FAIL';

export const CHECKOUT_DETAILS_REQUEST = 'CHECKOUT_DETAILS_REQUEST';
export const CHECKOUT_DETAILS_SUCCESS = 'CHECKOUT_DETAILS_SUCCESS';
export const CHECKOUT_DETAILS_FAIL = 'CHECKOUT_DETAILS_FAIL';