export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const LIST_ORDERS_REQUEST = 'LIST_ORDERS_REQUEST';
export const LIST_ORDERS_SUCCESS = 'LIST_ORDERS_SUCCESS';
export const LIST_ORDERS_FAIL = 'LIST_ORDERS_FAIL';

export const LIST_MY_ORDERS_REQUEST = 'LIST_MY_ORDERS_REQUEST';
export const LIST_MY_ORDERS_SUCCESS = 'LIST_MY_ORDERS_SUCCESS';
export const LIST_MY_ORDERS_FAIL = 'LIST_MY_ORDERS_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const MY_ORDER_DETAILS_REQUEST = 'MY_ORDER_DETAILS_REQUEST';
export const MY_ORDER_DETAILS_SUCCESS = 'MY_ORDER_DETAILS_SUCCESS';
export const MY_ORDER_DETAILS_FAIL = 'MY_ORDER_DETAILS_FAIL';

export const ORDER_UPDATE_PAID_REQUEST = 'ORDER_DUPDATE_PAIDREQUEST';
export const ORDER_UPDATE_PAID_SUCCESS = 'ORDER_UPDATE_PAID_SUCCESS';
export const ORDER_UPDATE_PAID_FAIL = 'ORDER_UPDATE_PAID_FAIL';

