export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';


export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';
export const GET_USER_PROFILE_RESET = 'GET_USER_PROFILE_RESET';

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_RESET = 'UPDATE_USER_PROFILE_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const LIST_USERS_REQUEST = 'LIST_USERS_REQUEST';
export const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS';
export const LIST_USERS_FAIL = 'LIST_USERS_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

// User Wishlist
export const WISHLIST_ADD_ITEM_REQUEST = 'WISHLIST_ADD_ITEM_REQUEST';
export const WISHLIST_ADD_ITEM_SUCCESS = 'WISHLIST_ADD_ITEM_SUCCESS';
export const WISHLIST_ADD_ITEM_FAIL = 'WISHLIST_ADD_ITEM_FAIL';
export const WISHLIST_ADD_ITEM_RESET = 'WISHLIST_ADD_ITEM_RESET';

export const WISHLIST_REMOVE_ITEM_REQUEST = 'WISHLIST_REMOVE_ITEM_REQUEST';
export const WISHLIST_REMOVE_ITEM_SUCCESS = 'WISHLIST_REMOVE_ITEM_SUCCESS';
export const WISHLIST_REMOVE_ITEM_FAIL = 'WISHLIST_REMOVE_ITEM_FAIL';

// User Cart
export const USER_CART_ADD_ITEM_REQUEST = 'USER_CART_ADD_ITEM_REQUEST';
export const USER_CART_ADD_ITEM_SUCCESS = 'USER_CART_ADD_ITEM_SUCCESS';
export const USER_CART_ADD_ITEM_FAIL = 'USER_CART_ADD_ITEM_FAIL';
export const USER_CART_ADD_ITEM_RESET = 'USER_CART_ADD_ITEM_RESET';

export const USER_CART_REMOVE_ITEM_REQUEST = 'USER_CART_REMOVE_ITEM_REQUEST';
export const USER_CART_REMOVE_ITEM_SUCCESS = 'USER_CART_REMOVE_ITEM_SUCCESS';
export const USER_CART_REMOVE_ITEM_FAIL = 'USER_CART_REMOVE_ITEM_FAIL';
export const USER_CART_REMOVE_ITEM_RESET = 'USER_CART_REMOVE_ITEM_RESET';

export const USER_CART_CLEAR_ITEMS_REQUEST = 'USER_CART_CLEAR_ITEMS_REQUEST';
export const USER_CART_CLEAR_ITEMS_SUCCESS = 'USER_CART_CLEAR_ITEMS_SUCCESS';
export const USER_CART_CLEAR_ITEMS_FAIL = 'USER_CART_CLEAR_ITEMS_FAIL';
export const USER_CART_CLEAR_ITEMS_RESET = 'USER_CART_CLEAR_ITEMS_RESET';

export const USER_CART_UPDATE_QUANTITY_REQUEST = 'USER_CART_UPDATE_QUANTITY_REQUEST';
export const USER_CART_UPDATE_QUANTITY_SUCCESS = 'USER_CART_UPDATE_QUANTITY_SUCCESS';
export const USER_CART_UPDATE_QUANTITY_FAIL = 'USER_CART_UPDATE_QUANTITY_FAIL';
export const USER_CART_UPDATE_QUANTITY_RESET = 'USER_CART_UPDATE_QUANTITY_RESET';

export const USER_CART_SAVE_PAYMENT_METHOD = 'USER_CART_SAVE_PAYMENT_METHOD';


