const teaList = [
    {
        id: 1,
        name: "earl gray",
        category: "loose leaf",
        type:"black tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/earl-grey.jpg",
        price: "9.25",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 2,
        name: "chai",
        category: "loose leaf",
        type:"black tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/chai.jpg",
        price: "10.00",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 3,
        name: "orange pekoe",
        category: "loose leaf",
        type:"black tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/orange-pekoe.jpg",
        price: "9.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 4,
        name: "jasmine",
        category: "loose leaf",
        type:"green tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/jasmine.jpg",
        price: "12.00",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 5,
        name: "caramel rooibos",
        category: "loose leaf",
        type:"red tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/caramel-rooibos.jpg",
        price: "10.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 6,
        name: "classic matcha",
        category: "matcha",
        type:"ceremonial matcha",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/matcha.jpg",
        price: "12.00",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 7,
        name: "pink iced tea",
        category: "tea mixes",
        type:"classic mixes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/pink-iced-tea.jpg",
        price: "8.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 8,
        name: "orange dream",
        category: "loose leaf",
        type:"black tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/orange-dream.jpg",
        price: "9.00",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 9,
        name: "chocolate oolong",
        category: "loose leaf",
        type:"oolong tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/chocolate-oolong.jpg",
        price: "10.25",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 10,
        name: "white rose",
        category: "loose leaf",
        type:"white tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/white-rose.jpg",
        price: "10.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 11,
        name: "chamomile",
        category: "loose leaf",
        type:"herbal tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/chamomile.jpg",
        price: "9.80",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 12,
        name: "maple",
        category: "matcha",
        type:"flavoured matcha",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/matcha-2.jfif",
        flavourImage: "/images/maple.jfif",
        price: "12.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 13,
        name: "strawberry",
        category: "matcha",
        type:"flavoured matcha",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/matcha-2.jfif",
        flavourImage: "/images/strawberries.jfif",
        price: "12.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 14,
        name: "peach",
        category: "matcha",
        type:"flavoured matcha",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/matcha-2.jfif",
        flavourImage: "/images/peaches.jfif",
        price: "12.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 15,
        name: "blueberry",
        category: "matcha",
        type:"flavoured matcha",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/matcha-2.jfif",
        flavourImage: "/images/blueberry.jfif",
        price: "12.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 16,
        name: "chocolate",
        category: "matcha",
        type:"flavoured matcha",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/matcha-2.jfif",
        flavourImage: "/images/chocolate.jfif",
        price: "12.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 17,
        name: "white chocolate",
        category: "matcha",
        type:"flavoured matcha",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/matcha-2.jfif",
        flavourImage: "/images/white-chocolate.jfif",
        price: "12.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 18,
        name: "apple",
        category: "loose leaf",
        type:"herbal tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/apple-tea.jfif",
        price: "9.80",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 19,
        name: "hibiscus",
        category: "loose leaf",
        type:"herbal tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/hibiscus-tea.jfif",
        price: "9.80",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 20,
        name: "sleepy",
        category: "loose leaf",
        type:"herbal tea",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/sleepy-tea.jfif",
        price: "9.80",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 21,
        name: "white tea margarita",
        category: "tea mixes",
        type:"cocktail mixes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/white-margarita.jfif",
        price: "9.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 22,
        name: "strawberry green tea daiquiri",
        category: "tea mixes",
        type:"cocktail mixes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/green-daiquiri.jfif",
        price: "9.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 23,
        name: "irish cream tea",
        category: "tea mixes",
        type:"cocktail mixes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/irish-cream-tea.jfif",
        price: "9.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 24,
        name: "blue dragonfruit",
        category: "tea mixes",
        type:"classic mixes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/blue-dragonfruit.jfif",
        price: "9.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 25,
        name: "blueberry black tea",
        category: "tea mixes",
        type:"classic mixes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/blueberry-black-tea.jfif",
        price: "9.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },
    {
        id: 26,
        name: "creamy chai",
        category: "tea mixes",
        type:"classic mixes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id eaque consequuntur, accusamus ab, ex, autem alias ullam itaque doloremque quisquam hic ipsa deleniti. Temporibus, voluptatum!",
        image: "/images/chai-mix.jfif",
        price: "9.50",
        ingredients: ["apple","orange","banana","cinnamon","tea"],
        amount: 1,

    },

]

export default teaList;